language: node_js

node_js:
  - 5.1.1

addons:
  ssh_known_hosts:
    - 162.243.207.143

branches:
  only:
    - master

env:
  global:
    - REMOTE_APP_DIR=/srv/www/node/app/
    - REMOTE_USER=deploy
    - REMOTE_HOST=162.243.207.143

before_install:
  - ./scripts/install.sh

script:
  - npm run test-travis

after_script:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf coverage
  - rm -rf *

after_success:
  - ./scripts/deploy.sh
